/* Auto-generated by genmsg_cpp for file /home/saurabh/Documents/Thesis/ROS/my_pcl_tutorial/msg/GroundPlaneCoeff.msg */
#ifndef MY_PCL_TUTORIAL_MESSAGE_GROUNDPLANECOEFF_H
#define MY_PCL_TUTORIAL_MESSAGE_GROUNDPLANECOEFF_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace my_pcl_tutorial
{
template <class ContainerAllocator>
struct GroundPlaneCoeff_ {
  typedef GroundPlaneCoeff_<ContainerAllocator> Type;

  GroundPlaneCoeff_()
  : header()
  , a(0.0)
  , b(0.0)
  , c(0.0)
  , d(0.0)
  {
  }

  GroundPlaneCoeff_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , a(0.0)
  , b(0.0)
  , c(0.0)
  , d(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _a_type;
  double a;

  typedef double _b_type;
  double b;

  typedef double _c_type;
  double c;

  typedef double _d_type;
  double d;


  typedef boost::shared_ptr< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GroundPlaneCoeff
typedef  ::my_pcl_tutorial::GroundPlaneCoeff_<std::allocator<void> > GroundPlaneCoeff;

typedef boost::shared_ptr< ::my_pcl_tutorial::GroundPlaneCoeff> GroundPlaneCoeffPtr;
typedef boost::shared_ptr< ::my_pcl_tutorial::GroundPlaneCoeff const> GroundPlaneCoeffConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace my_pcl_tutorial

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7543c8ecc51b07e301a29f823a098207";
  }

  static const char* value(const  ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7543c8ecc51b07e3ULL;
  static const uint64_t static_value2 = 0x01a29f823a098207ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_pcl_tutorial/GroundPlaneCoeff";
  }

  static const char* value(const  ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 a\n\
float64 b\n\
float64 c\n\
float64 d\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.a);
    stream.next(m.b);
    stream.next(m.c);
    stream.next(m.d);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GroundPlaneCoeff_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::my_pcl_tutorial::GroundPlaneCoeff_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MY_PCL_TUTORIAL_MESSAGE_GROUNDPLANECOEFF_H

